/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        english: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.


Zoom level info
defualt is 0
zoomout max is -6 low detail
zoomin max is 3 high detail

*/

UnminedCustomMarkers = {

    isEnabled: true,

    markersData: [

        // Example 1: Simple marker
        //{
        //    x: -200,
        //    z: -200,
        //    image: "custom.pin.png",
        //    imageAnchor: [0.5, 1],
        //    imageScale: 0.5,
        //},

        // Example 2: Marker with text
        //{
        //    x: 0,
        //    z: 0,
        //    image: "custom.pin.png",
        //    imageAnchor: [0.5, 1],
        //    imageScale: 0.5,
        //    english: "Marker with text",
        //    textColor: "red", 
        //    offsetX: 0,
        //    offsetY: 20,
        //    font: "bold 20px Calibri,sans serif",
        //},

        // Example 3: Text only
        //{
        //    x: 200,
        //    z: 200,
        //    english: "Text only", 
        //    textColor: "yellow", 
        //    offsetX: 0,
        //    offsetY: 0, 
        //    font: "bold 50px Calibri,sans serif",
        //},
        {
            x: -845,
            z: 674,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -1026,
            z: 709,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -852,
            z: 866,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -482,
            z: 548,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -275,
            z: 519,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -117,
            z: 128,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -12,
            z: 2,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: -91,
            z: -102,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 12015,
            z: -59,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 13625,
            z: 11,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 13878,
            z: 405,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 15017,
            z: -975,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 5,
            z: -523,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 203,
            z: -1635,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 148,
            z: -2283,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 372,
            z: -4380,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        {
            x: 1404,
            z: -9769,
            image: "chasm.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
        },
        // SILVERTON
        {
            x: -97,
            z: 142,
            image: "silverton.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.1,
            english: "Silverton",
            japanese: "シルバートン",
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 30px Verdana,sans serif",
            minZoom: -2,
            maxZoom: 1,
        },
        {
            x: -533,
            z: 569,
            image: "castle.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Charo's Castle",
            japanese: "ちゃろの城",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: -270,
            z: 527,
            image: "base.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Rianu & Geo",
            japanese: "りあぬとGeo",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: -746,
            z: 878,
            image: "castle.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Air's Castle",
            japanese: "エアーの城",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: -1002,
            z: 667,
            image: "city.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Sekisui Town",
            japanese: "セキスイタウン",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: -1063,
            z: 711,
            image: "zoo.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Sekisui Zoo",
            japanese: "セキスイの動物園",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom: 1,
        },
        {
            x: -844,
            z: 721,
            image: "aquarium.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Aquarium",
            japanese: "水族館",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom: 1,
        },
        {
            x: -1892,
            z: 578,
            image: "castle.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Integrity's Castle",
            japanese: "インテグリティの城",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: -683,
            z: -857,
            image: "town.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Juelsman's Village",
            japanese: "ジュールスマンの村",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: 1373,
            z: -9735,
            image: "town.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Christmas Town",
            japanese: "クリスマスタウン",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: 13771,
            z: 542,
            image: "japanesecastle.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.08,
            english: "Hitsuji Castle",
            japanese: "羊城",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: 13808,
            z: 649,
            image: "japanesetown.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.06,
            english: "Hitsuji Castle Town",
            japanese: "羊城下町",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 18px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: 13584,
            z: 456,
            image: "japanesetown.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.06,
            english: "Hitsuji Village",
            japanese: "羊村",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 18px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        
        //VILLAGES
        
        {
            x: 236,
            z: 610,
            image: "town.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "Village",
            japanese: "村",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        {
            x: 14455,
            z: -224,
            image: "japanesetown.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "Village",
            japanese: "村",
            textColor: "#FFFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 20,
            font: "bold 16px Verdana,sans serif",
            minZoom:-2,
            maxZoom: 1,
        },
        //Routes
        {
            x: -50,
            z: -975,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 50,
            z: -100,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 88,
            z: -1967,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 276,
            z: -2926,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 419,
            z: -4125,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -292,
            z: -5103,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 212,
            z: -6041,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "1",
            japanese: "1",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },

        {
            x: -361,
            z: 513,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "2",
            japanese: "2",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -221,
            z: 286,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "2",
            japanese: "2",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -671,
            z: 649,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "2",
            japanese: "2",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -1313,
            z: 673,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "2",
            japanese: "2",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },

        {
            x: 147,
            z: 230,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "3",
            japanese: "3",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 78,
            z: 998,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "3",
            japanese: "3",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: 300,
            z: 1876,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "3",
            japanese: "3",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -123,
            z: 2615,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "3",
            japanese: "3",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },
        {
            x: -65,
            z: 3342,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "3",
            japanese: "3",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },

        {
            x: -252,
            z: 3,
            image: "route.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.05,
            english: "4",
            japanese: "4",
            textColor: "#FFFFFFF", 
            offsetX: 0,
            offsetY: -12,
            font: "20px Verdana,sans serif",
        },

        {
            x: -19,
            z: 1197,
            image: "FM.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
            english: "2",
            japanese: "2",
            textColor: "#000000", 
            offsetX: 0,
            offsetY: -10,
            font: "15px Verdana,sans serif",
        },
        {
            x: -286,
            z: 1165,
            image: "FM.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
            english: "2",
            japanese: "2",
            textColor: "#000000", 
            offsetX: 0,
            offsetY: -10,
            font: "15px Verdana,sans serif",
        },
        {
            x: -693,
            z: 1077,
            image: "FM.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
            english: "2",
            japanese: "2",
            textColor: "#000000", 
            offsetX: 0,
            offsetY: -10,
            font: "15px Verdana,sans serif",
        },

        {
            x: -250,
            z: 2651,
            image: "FM.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
            english: "5",
            japanese: "5",
            textColor: "#000000", 
            offsetX: 0,
            offsetY: -10,
            font: "15px Verdana,sans serif",
        },
        {
            x: -554,
            z: 2391,
            image: "FM.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.03,
            english: "5",
            japanese: "5",
            textColor: "#000000", 
            offsetX: 0,
            offsetY: -10,
            font: "15px Verdana,sans serif",
        },

        
        //PLACE NAMES
        {
            x: -7,
            z: 2310,
            english: "Firefly Lake", 
            japanese: "ホタル湖",
            textColor: "#FFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 0, 
            font: "bold 20px Verdana,sans serif",
        },

        {
            x: -1051,
            z: 2996,
            english: "Southern Ocean",
            japanese: "南極海",
            textColor: "#FFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 0, 
            font: "bold 20px Verdana,sans serif",
        },

        {
            x: 76,
            z: 31,
            english: "Mount Silver", 
            japanese: "シルバー山",
            textColor: "#FFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 0, 
            font: "bold 20px Verdana,sans serif",
        },

        {
            x: 13620,
            z: -37,
            english: "Pigman Forest", 
            japanese: "ピッグマンの森",
            textColor: "#FFFFFF", 
            dropShadowColor: "#625717FF", // Add this to enable drop shadow
            offsetX: 0,
            offsetY: 0, 
            font: "bold 20px Verdana,sans serif",
        },
        
        // do not delete the following two closing brackets
    ]
    ,
    generateMarkers: function(language) {
        return this.markersData.map(function(marker) {
            const newMarker = Object.assign({}, marker);
            // Set text based on selected language
            newMarker.text = language === 'en' ? marker.english : marker.japanese;
            // Delete the english and japanese properties to avoid confusion
            delete newMarker.english;
            delete newMarker.japanese;
            return newMarker;
        });
    },

    // Initial markers (English by default)
    markers: []
}
